### PR TITLE
Added browserify-incremental support

### PR DESCRIPTION
**Pull request by taoeffect**
- New: Added `cacheFile` option for [browserify-incremental](https://github.com/jsdf/browserify-incremental) support
- Update dependencies and added package-lock.json (for npm 5+)

Bumped version to 5.2.0

### CODE REVIEW

**Comment by DirtyHairy** [comment]
Thanks for the PR! I just tested it, and it works nicely. Some remarks before I merge:

* Could you please remove the package-lock.json? I am not yet convinced that having a lockfile in a NPM package is a good idea :smirk:
* Could you revert the contributors change in `package.json`? While I value your contribution, no other contributor (besides Justin and Tommy) is mentioned in the manifest, so I feel this would be a bit unfair to those.
* Is there a specific reason why you are globally caching the decorated runners in the `destinations` array?

Again, thanks a lot, looking forward to merge this.

**Comment by taoeffect** [comment]
> Could you please remove the lockfile? I am not yet convinced that having a lockfile in a NPM package is a good idea :smirk:

I am convinced that it is a good idea, so before I remove it maybe we should discuss that out?

> Could you revert the contributors change in package.json? While I value your contribution, no other contributor (besides Justin and Tommy) is mentioned in the manifest, so I feel this would be a bit unfair to those.

Sure thing.

> Is there a specific reason why you are globally caching the decorated runners in the `destinations` array?

Yes, that was my idea of how to persist the created browserify instances between calls from `grunt-contrib-watch`. If you have a better idea I'm all ears.

**Comment by taoeffect** [comment]
> I am convinced that it is a good idea, so before I remove it maybe we should discuss that out?

FYI, having that lock file around is standard usage of NPM since version 5. It's effectively a somewhat of a security/integrity check.

**Comment by DirtyHairy** [comment]
>  FYI, having that lock file around is standard usage of NPM since version 5. It's effectively somewhat of a security/integrity check.

Afaik, NPM will neither publish `package-lock.json` nor heed it if one is found in a installed dependency. From the [documentation](https://docs.npmjs.com/files/package-lock.json):
> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

So, having a lockfile around in a NPM package will only ensure that test with stale dependency versions that actual consumers get installed when using my package :smirk:

> Yes, that was my idea of how to persist the created browserify instances between calls from grunt-contrib-watch. If you have a better idea I'm all ears.

I am not opposed to caching or your way of doing so. I just wondered whether there is a reason that requires caching --- if not, I would be inclined to remove it as it complicates the code and is not done for "regular" builds, either.

**Comment by taoeffect** [comment]
> So, having a lockfile around in a NPM package will only ensure that test with stale dependency versions that actual consumers get installed when using my package :smirk:

Not sure I fully understand that sentence, sorry. But the file is good for at least the developers who contribute to this software, and keeping version integrity is indirectly helpful to the end-users of the library as well.

>  I just wondered whether there is a reason that requires caching

Yes, I don't believe it worked as well without it, if I remember correctly. From the documentation of browserify-incremental you can see that [it's designed](https://github.com/jsdf/browserify-incremental#var-b--browserifyincopts) to have `.bundle` called multiple times on the same instance.

**Comment by DirtyHairy** [comment]
> Not sure I fully understand that sentence, sorry. But the file is good for at least the developers who contribute to this software, and keeping integrity is indirectly helpful to the end-users of the library as well.

Sorry, it was late and my wording was not very clear (*and* full of  typos :smirk:) To elaborate a bit more: the purpose of the lockfile is to ensure that anyone **deploying / running** a package gets the exact same set of dependencies. Without it, there is no chance of getting 100% reproducible behavior or builds, and I have been scorched by that often enough to appreciate it. However, dependency locking arguably should happen at the top level package, and this is precisely what is enforced by NPM: lockfiles further down the dependency graph are ignored.

Now, if we're talking about a library, I don't see any value in the lockfile. A consumer will not run the package directly, but install it as a dependency, so he will be guranteed to get a dependency tree that differs from that recorded in the lockfile. I see this as an issue, because I want the set of dependencies used during development to match those installed by a consumer as closely as possible. The lockfile does not get me any closer to this goal --- it makes it even harder to achieve.

> Yes, I don't believe it worked as well without it, if I remember correctly. From the documentation of browserify-incremental you can see that it's designed to have .bundle called multiple times on the same instance.

At the very least, it will save rereading the cache :smirk: Let's keep it. This gets my list of changes down to removing the lockfile :smiling_imp: One last thing: could you squash the commits after you're done into one single commit?

**Comment by taoeffect** [comment]
> However, dependency locking arguably should happen at the top level package, and this is precisely what is enforced by NPM: lockfiles further down the dependency graph are ignored.
> 
> Now, if we're talking about a library, I don't see any value in the lockfile. A consumer will not run the package directly, but install it as a dependency, so he will be guranteed to get a dependency tree that differs from that recorded in the lockfile. I see this as an issue, because I want the set of dependencies used during development to match those installed by a consumer as closely as possible. The lockfile does not get me any closer to this goal --- it makes it even harder to achieve.

Perhaps this is a misunderstanding? My understanding is that a package-lock.json file is just as useful to libraries as it is to anything else. While yes, you are correct that the package-lock.json files of dependencies are ignored, that is because they're not distributed by NPM, and so in no way negatively affect any application that is using the library as a dependency.

Instead, they are useful for preserving integrity among the development team, so that you can tell when one developer's data has gotten out of sync with another developer's data.

This is very useful for security reasons, and as far as I can see, there is zero downside to having it in the repo, only an upside to the project developers.

If developer Bob requests `package-a` from NPM, the contents of that package should match whatever the `package-lock.json` file says. If they do not match, that means Bob might have been targeted by malware.

So this is a safety precaution for you and everyone else who contributes to this project.

Unless I am missing something (?), there should be no negative outcome from adding this to the repo, and it would give some modicum of extra security to not only yourself, but people like me who want to contribute.

> One last thing: could you squash the commits after you're done into one single commit?

I can yes, but currently we are referencing my fork of this project using the commit I originally pushed. If I destroy that commit it will break the other devs who are using my fork. I believe GitHub allows you to do a [squash merge](https://github.com/blog/2141-squash-your-commits) via the interface, no?

**Comment by DirtyHairy** [comment]
> Perhaps this is a misunderstanding?

I guess there is --- we have different perspectives on the role of the lockfile. The primary purpose of a lockfile is freezing the dependency tree in order to have a reproducible `node_modules` directory. It also records hashes of the packages (in addition to the version), and you could look at that as a security device that protects you from corrupt or compromised package tarballs, but that's not its primary purpose.

If I merge your lockfile, it will lock the dependecy tree I get when doing `npm install` during development to the precise versions **you** got when doing `npm install`. However this will differ from the dependency tree that anyone else  who installs `grunt-browserify` as a dependency into their projects gets (in a few days the very latest).  As I (and anyone else for that matter) need to test the behavior of `grunt-browserify` with current versions of its dependencies (because that's what anyone *using* it gets), I (and anyone else) would have to update the lockfile whenever they do development which defeats its purpose.

So, again, please remove it from the PR. I can do so myself after the merge, but I prefer not to mess with other peoples' contributions immediatelly after merging them (I think this is rude).

> I believe GitHub allows you to do a squash merge via the interface, no?

Indeed it does, I'll squash via the web interface then.

**Comment by taoeffect** [comment]
I can certainly remove the file if you insist, but I think your understanding of the lock file is mistaken, and you may be confusing it with the shrinkwrap file.

From [NPM's documentation](https://docs.npmjs.com/files/package-lock.json):

> This file is intended to be committed into source repositories, and serves various purposes:

And also [this wonderful post](https://jpospisil.com/2017/06/02/understanding-lock-files-in-npm-5.html) by @jiripospisil:

> When working on a library
> 
> If you’re working on a library (as in a package onto which others will depend on), you should use the new lock file. An alternative is to use shrinkwrap but make sure it never gets published with the package (the new lock file is never published automatically). Why not publish the shrinkwrap? [..]

There is a good reason that NPM creates this file by default now, and as above, it's intended to be committed to repositories, including libraries.

> If I merge your lockfile, it will lock the dependecy tree I get when doing npm install during development to the precise versions **you** got when doing npm install.

Yes... but the versions that I got are the ones that are dictated by the `package.json` file, which is something that you the project maintainer (and other contributors) have specified.

There is nothing at all bad about that.

> However this will differ from the dependency tree that anyone else who installs grunt-browserify as a dependency into their projects gets (in a few days the very latest).

I'm not sure what you mean by that. Are you referring to the fact that this project's package.json file specifies versions using the caret `^` character?

If that is a concern for you, then you can force precise versions by setting `save-exact = true` in an `.npmrc` file, and then the versions that are installed by everyone, including users who list `grunt-browserify` as a dependency, will be exactly the same. Note that that is an issue regardless of whether or not this project has the `package-lock.json` file in its repo (and in fact is why for our projects we set `save-exact = true`.

If you'd like, I can amend this PR with an `.npmrc` to do that, and update `package.json` with precise versions.

However, as I'm not aware of any good reason to remove the `package-lock.json` file, and can only think of problems that could result as of doing so, I have no plans to remove the file from my fork. You are of course welcome to merge this and remove it manually if you really don't like it for whatever reason, but in that case I will just continue to use my fork. :-\

**Comment by taoeffect** [comment]
> Yes... but the versions that I got are the ones that are dictated by the `package.json` file, which is something that you the project maintainer (and other contributors) have specified.

To clarify that further: the `package-lock.json` file is kept in sync by npm with the `package.json` file.

**Comment by DirtyHairy** [comment]
I have merged the PR and removed the lockfile in a subsequent commit myself. I'm sorry, but I think you are mistaken on some aspects of dependency locking and the lockfile:

* Pinning semvers in `package.json` will only pin direct dependencies, not any nested dependencies: that's what the lockfile is for.
* `npm-shrinkwrap.json` and `package-lock.json` do the same, just the semantics regarding publishing and installation of the package as a dependency are different.
* The section `When working on a library` of the blogpost you link only advocates using `package-lock.json` over `npm-shrinkwrap.json`. Other than that, it verbalizes my concerns pretty well: the lockfile keeps me from catching any errors during development that actual users might get due to updated dependecies and subdependencies. In fact, not committing the lockfile is one of the options suggested by the blogpost. As changes to `grunt-browserify` are pretty rare, that's the most convenient road for me to take.

I have done the merge locally and github doesn't pick it up, so I'll just close this PR ;) Again, thanks for your contribution!

**Comment by taoeffect** [comment]
No problem, that's your call as maintainer and I respect it.

> Other than that, it verbalizes my concerns pretty well: the lockfile keeps me from catching any errors during development that actual users might get due to updated dependecies and subdependencies.

I've re-read that section in the post, and I do not see how or why that is a concern at all.

If you do `save-exact = true`, there is no problem. The `^` in my opinion is an anti-pattern introduced by NPM, and nobody should use it for exactly those reasons. The lock file, OTOH, is a step forward.

**Comment by DirtyHairy** [comment]
> If you do save-exact = true, there is no problem.

But this is not exactly true. Even if you pin your dependencies to exact versions in `package.json`, this will still not pin the versions of their respective dependencies: you pin package `foo` to, say 1.2.7, but `foo` again depends on `bar@^1.2.6`, and this means developer A will get `bar@1.2.8` pulled in, while B might get `bar@1.3.2` installed. The lockfile is the only way to gurantee reproducible dependencies beyond the first level.

I agree that node's way of versioning dependencies is flawed, and I also agree that NPM finally writing lockfiles by default is good news. I just question their value for libraries which cannot control their own dependency tree by design anyway :smirk:

**Comment by taoeffect** [comment]
> Even if you pin your dependencies to exact versions in package.json, this will not pin the versions of their respective dependencies

That is a good point that I hadn't thought of, but I don't see how *not having* the lock file is a solution to it. If you don't have the lock file, that can still happen.

OTOH, if the entire node ecosystem moves to having lock files and `save-exact = true`, that will make everyone's life easier by making that scenario less likely to happen. _\*shrug\*_

**Comment by DirtyHairy** [comment]
> That is a good point that I hadn't thought of, but I don't see how not having the lock file is a solution to it. If you don't have the lock file, that can still happen.

It is not so much that I want to fully pin the dependencies of my packages (for good or bad, NPM and the ecosystem do not work this way), but I see no value in fixing the dependency tree during development with a lockfile if I know for a fact that my users will be running with different dependencies. My reasoning is that this will only mask breaks that users might encounter due to pulling in more recent subdependecies during installation :smirk:

> OTOH, if the entire node ecosystem moves to having lock files and save-exact = true, that will make everyone's life easier by making that scenario less likely to happen. *shrug*

Agreed. This issue is why we have been using shrinkwrappers for professional node projects (applications, not libraries) for the last few years.

**Pull request closed without merging**
