### PR TITLE
Fixing issue where plugin was still writing to stream when closed off

### PR DESCRIPTION
**Pull request by justinjmoses**
This is incomplete (missing the `options.banner` prepend, and broken tests) but I did find the culprit of #350. 

Basically, instead of using the `bundle` callback, we need to `pipe` instead (see [here](https://github.com/jmreidy/grunt-browserify/pull/351/files#diff-b3b53682a18f203ac8d29b0e277cad26R162)), as the latter ensures that the entire `pipeline` is complete before piping. In this case - that all the files in the pipeline have completed. (You can [see factor-bundle here](https://github.com/substack/factor-bundle/blob/master/index.js#L102) is adding the files to the browserify pipeline).

That said, I'm not using the grunt writer - I'm not that familiar with grunt - is that a concern?

This is obviously a significant change, and hence I wanted to run it by you first @tleunen. (Also, I changed the `self` to `bind(this)` as I went along, as I loathe the `self = this` pattern. It's not a deal-breaker though by any means)

### CODE REVIEW

**Comment by justinjmoses** [comment]
Ugh - this doesn't seem to be working. I'm still getting intermittent failures

**Comment by justinjmoses** [comment]
As mentioned in issue, it is due to this reality: https://github.com/substack/factor-bundle/issues/61

**Comment by tleunen** [comment]
Nice find. Hopefully you'll find a way to solve this

**Comment by justinjmoses** [comment]
This is one solution, but requires modifying both `factor-bundle` to return the output streams and having `grunt-browserify` listen for them specifically (sub-optimal). https://github.com/substack/factor-bundle/issues/61#issuecomment-135480826

What I'd prefer is to have factor-bundle inject the streams it has into the `wrap` part of the browserify pipeline, such that b.`end` would only emit when the common and ALL the factor-bundles are complete, but as I mentioned there, I'm struggling to understand how do do that.

**Pull request closed without merging**
